services:
  web:
    build: .
    container_name: fastapi_app
    expose:
      - "8000"
    volumes:
      - .:/app
      - /app/.venv
    env_file:
      - .env
    networks:
      - shoponbot_shared_net
    depends_on:
      - redis
      - db
      - rabbitmq

  # Nginx service
  ngnix:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - shoponbot_shared_net
    depends_on:
      - web

  # 2. Redis Caching Service
  redis:
    image: redis:alpine
    container_name: redis-fastapi
    ports:
      - "6379:6379"
    networks:
      - shoponbot_shared_net

  # 3. postgres db
  db:
    image: postgres:17-alpine
    container_name: postgres-fastapi
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ShopOnBot_db

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shoponbot_shared_net

  # RabbitMQ service
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbit_mq
    ports:
      - "5672:5672" # RabbitMQ protocol 
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest 
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - shoponbot_shared_net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # RabbitMQ email worker
  worker:
    build: .
    container_name: email_worker
    command: >
      uv run python -m app.workers.email_worker
    volumes:
      - .:/app
      - /app/.venv
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - shoponbot_shared_net
    depends_on:
      rabbitmq:
        condition: service_healthy

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka_broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,CLUSTER:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka_broker:29092,CLUSTER://127.0.0.1:9092'
      KAFKA_OFFERS_LISTENERS: 'PLAINTEXT://0.0.0.0:29092,CLUSTER://0.0.0.0:9092'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:29092,CLUSTER://0.0.0.0:9092,CONTROLLER://0.0.0.0:29093'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka_broker:29093'
    networks:
      - shoponbot_shared_net

volumes:
  postgres_data:

networks:
  shoponbot_shared_net:
    name: shoponbot-production-network
    driver: bridge
